site_name: User Guide
site_url: https://lingsv.github.io/nivensdocs/

nav:
  - Home: index.md
  - Novo Cadastro: cadastro.md
  - Relatório: report.md
  - Editar Funcionário: editar.md
  - Senha de Gestão: senha.md
  - Administração do Sistema: admin.md

theme:
   name: material
   palette:
      primary: cyan
      accent: indigo
   font:
     text: Poppins
   features: 
      - navigation.top
   language: pt
extra:
   social:
   - icon: fontawesome/brands/github
     link: https://github.com/lingsv/Nivens
   - icon: fontawesome/brands/discord
     link: ""
       

