site_name: User Guide
site_url: ""

nav:
  - Home: index.md
  - Novo Cadastro: cadastro.md
  - Relatório: report.md
  - Editar Funcionário: editar.md
  - Senha de Gestão: senha.md
  - Administração do Sistema: admin.md

theme:
   name: material
   palette:
      primary: deep-purple
      accent: indigo
   font:
     text: Poppins
   features: 
      - navigation.top
   language: pt

